version: '3'

services:
  magic-button:
    container_name: magic-button
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    volumes:
      - ./:/magic-button
    networks:
      - clbb

networks:
  clbb:
    external: true
